// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcTAPt5QtIveXT8MgjncI0MSvUbBx3ET4',
    appId: '1:431849700069:web:37b42778b01196b4ccb20c',
    messagingSenderId: '431849700069',
    projectId: 'klontong-a10a4',
    authDomain: 'klontong-a10a4.firebaseapp.com',
    storageBucket: 'klontong-a10a4.firebasestorage.app',
    measurementId: 'G-ZB6TQ0844W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5m3Mn7fTYgY_11RIuemF0t-Og6DhhCUo',
    appId: '1:431849700069:android:91ee9d001fbe3046ccb20c',
    messagingSenderId: '431849700069',
    projectId: 'klontong-a10a4',
    storageBucket: 'klontong-a10a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEgeCueWWp9aY0uzQf9OFqw95A4m4dKpk',
    appId: '1:431849700069:ios:b1f9030568cde9d8ccb20c',
    messagingSenderId: '431849700069',
    projectId: 'klontong-a10a4',
    storageBucket: 'klontong-a10a4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEgeCueWWp9aY0uzQf9OFqw95A4m4dKpk',
    appId: '1:431849700069:ios:b1f9030568cde9d8ccb20c',
    messagingSenderId: '431849700069',
    projectId: 'klontong-a10a4',
    storageBucket: 'klontong-a10a4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcTAPt5QtIveXT8MgjncI0MSvUbBx3ET4',
    appId: '1:431849700069:web:d1f5c65eae92b76dccb20c',
    messagingSenderId: '431849700069',
    projectId: 'klontong-a10a4',
    authDomain: 'klontong-a10a4.firebaseapp.com',
    storageBucket: 'klontong-a10a4.firebasestorage.app',
    measurementId: 'G-CESQBCX63E',
  );
}
